// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Agl.Cdr.Common.Models
{
    /// <summary> Percentage of calls within the performance thresholds. </summary>
    public partial class PerformanceMetrics
    {
        /// <summary> Initializes a new instance of PerformanceMetrics. </summary>
        internal PerformanceMetrics()
        {
            PreviousDays = new List<float>();
        }

        /// <summary> Initializes a new instance of PerformanceMetrics. </summary>
        /// <param name="currentDay"> Percentage of calls within the performance threshold for the current day. 0.0 means 0%. 1.0 means 100%. </param>
        /// <param name="previousDays"> Percentage of calls within the performance threshold for previous days. The first element indicates yesterday and so on. A maximum of seven entries is required if available. 0.0 means 0%. 1.0 means 100%. </param>
        internal PerformanceMetrics(float? currentDay, IReadOnlyList<float> previousDays)
        {
            CurrentDay = currentDay;
            PreviousDays = previousDays;
        }

        /// <summary> Percentage of calls within the performance threshold for the current day. 0.0 means 0%. 1.0 means 100%. </summary>
        public float? CurrentDay { get; }
        /// <summary> Percentage of calls within the performance threshold for previous days. The first element indicates yesterday and so on. A maximum of seven entries is required if available. 0.0 means 0%. 1.0 means 100%. </summary>
        public IReadOnlyList<float> PreviousDays { get; }
    }
}
