/*
 * CDR Admin API
 *
 * Data Holder Consumer Data Standards Administration End Points created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker
 *
 * The version of the OpenAPI document: 1.15.0
 * Contact: contact@consumerdatastandards.gov.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Admin.Apis;
using Agl.Cdr.Admin.Models;
using Agl.Cdr.Admin.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Admin.Test.Model
{
    /// <summary>
    ///  Class for testing AverageResponseMetricsV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AverageResponseMetricsV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AverageResponseMetricsV2
        //private AverageResponseMetricsV2 instance;

        public AverageResponseMetricsV2Tests()
        {
            // TODO uncomment below to create an instance of AverageResponseMetricsV2
            //instance = new AverageResponseMetricsV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AverageResponseMetricsV2
        /// </summary>
        [Fact]
        public void AverageResponseMetricsV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" AverageResponseMetricsV2
            //Assert.IsType<AverageResponseMetricsV2>(instance);
        }


        /// <summary>
        /// Test the property 'Unauthenticated'
        /// </summary>
        [Fact]
        public void UnauthenticatedTest()
        {
            // TODO unit test for the property 'Unauthenticated'
        }
        /// <summary>
        /// Test the property 'HighPriority'
        /// </summary>
        [Fact]
        public void HighPriorityTest()
        {
            // TODO unit test for the property 'HighPriority'
        }
        /// <summary>
        /// Test the property 'LowPriority'
        /// </summary>
        [Fact]
        public void LowPriorityTest()
        {
            // TODO unit test for the property 'LowPriority'
        }
        /// <summary>
        /// Test the property 'Unattended'
        /// </summary>
        [Fact]
        public void UnattendedTest()
        {
            // TODO unit test for the property 'Unattended'
        }
        /// <summary>
        /// Test the property 'LargePayload'
        /// </summary>
        [Fact]
        public void LargePayloadTest()
        {
            // TODO unit test for the property 'LargePayload'
        }
        /// <summary>
        /// Test the property 'Secondary'
        /// </summary>
        [Fact]
        public void SecondaryTest()
        {
            // TODO unit test for the property 'Secondary'
        }
        /// <summary>
        /// Test the property 'LargeSecondary'
        /// </summary>
        [Fact]
        public void LargeSecondaryTest()
        {
            // TODO unit test for the property 'LargeSecondary'
        }

    }

}
