/*
 * CDR Admin API
 *
 * Data Holder Consumer Data Standards Administration End Points created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker
 *
 * The version of the OpenAPI document: 1.15.0
 * Contact: contact@consumerdatastandards.gov.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Admin.Apis;
using Agl.Cdr.Admin.Models;
using Agl.Cdr.Admin.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Admin.Test.Model
{
    /// <summary>
    ///  Class for testing InvocationMetricsV2LargePayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvocationMetricsV2LargePayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InvocationMetricsV2LargePayload
        //private InvocationMetricsV2LargePayload instance;

        public InvocationMetricsV2LargePayloadTests()
        {
            // TODO uncomment below to create an instance of InvocationMetricsV2LargePayload
            //instance = new InvocationMetricsV2LargePayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvocationMetricsV2LargePayload
        /// </summary>
        [Fact]
        public void InvocationMetricsV2LargePayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" InvocationMetricsV2LargePayload
            //Assert.IsType<InvocationMetricsV2LargePayload>(instance);
        }


        /// <summary>
        /// Test the property 'CurrentDay'
        /// </summary>
        [Fact]
        public void CurrentDayTest()
        {
            // TODO unit test for the property 'CurrentDay'
        }
        /// <summary>
        /// Test the property 'PreviousDays'
        /// </summary>
        [Fact]
        public void PreviousDaysTest()
        {
            // TODO unit test for the property 'PreviousDays'
        }

    }

}
