/*
 * CDR Admin API
 *
 * Data Holder Consumer Data Standards Administration End Points created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker
 *
 * The version of the OpenAPI document: 1.15.0
 * Contact: contact@consumerdatastandards.gov.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Admin.Apis;
using Agl.Cdr.Admin.Models;
using Agl.Cdr.Admin.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Admin.Test.Model
{
    /// <summary>
    ///  Class for testing RequestMetaDataUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestMetaDataUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestMetaDataUpdate
        //private RequestMetaDataUpdate instance;

        public RequestMetaDataUpdateTests()
        {
            // TODO uncomment below to create an instance of RequestMetaDataUpdate
            //instance = new RequestMetaDataUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestMetaDataUpdate
        /// </summary>
        [Fact]
        public void RequestMetaDataUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestMetaDataUpdate
            //Assert.IsType<RequestMetaDataUpdate>(instance);
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }

    }

}
