/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Agl.Cdr.Energy.Converters;

namespace Agl.Cdr.Energy.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class EnergyServicePointListResponseData : IEquatable<EnergyServicePointListResponseData>
    {
        /// <summary>
        /// Gets or Sets ServicePoints
        /// </summary>
        [Required]
        [DataMember(Name="servicePoints", EmitDefaultValue=false)]
        public List<EnergyServicePoint> ServicePoints { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EnergyServicePointListResponseData {\n");
            sb.Append("  ServicePoints: ").Append(ServicePoints).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EnergyServicePointListResponseData)obj);
        }

        /// <summary>
        /// Returns true if EnergyServicePointListResponseData instances are equal
        /// </summary>
        /// <param name="other">Instance of EnergyServicePointListResponseData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EnergyServicePointListResponseData other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ServicePoints == other.ServicePoints ||
                    ServicePoints != null &&
                    other.ServicePoints != null &&
                    ServicePoints.SequenceEqual(other.ServicePoints)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ServicePoints != null)
                    hashCode = hashCode * 59 + ServicePoints.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(EnergyServicePointListResponseData left, EnergyServicePointListResponseData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EnergyServicePointListResponseData left, EnergyServicePointListResponseData right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
