/*
 * CDR Common API
 *
 * Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right
 *
 * The version of the OpenAPI document: 1.15.0
 * Contact: contact@consumerdatastandards.gov.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Agl.Cdr.Common.Client;
using Agl.Cdr.Common.Apis;
// uncomment below to import models
//using Agl.Cdr.Common.Models;

namespace Agl.Cdr.Common.Test.Api
{
    /// <summary>
    ///  Class for testing DiscoveryApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DiscoveryApiTests : IDisposable
    {
        private DiscoveryApi instance;

        public DiscoveryApiTests()
        {
            instance = new DiscoveryApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DiscoveryApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DiscoveryApi
            //Assert.IsType<DiscoveryApi>(instance);
        }

        /// <summary>
        /// Test GetOutages
        /// </summary>
        [Fact]
        public void GetOutagesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xV = null;
            //string xMinV = null;
            //var response = instance.GetOutages(xV, xMinV);
            //Assert.IsType<ResponseDiscoveryOutagesList>(response);
        }

        /// <summary>
        /// Test GetStatus
        /// </summary>
        [Fact]
        public void GetStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xV = null;
            //string xMinV = null;
            //var response = instance.GetStatus(xV, xMinV);
            //Assert.IsType<ResponseCommonDiscoveryStatus>(response);
        }
    }
}
