/*
 * CDR Admin API
 *
 * Data Holder Consumer Data Standards Administration End Points created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker
 *
 * The version of the OpenAPI document: 1.15.0
 * Contact: contact@consumerdatastandards.gov.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Apis;
using Org.OpenAPITools.Agl.Cdr.Admin;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PerformanceMetrics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PerformanceMetricsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PerformanceMetrics
        //private PerformanceMetrics instance;

        public PerformanceMetricsTests()
        {
            // TODO uncomment below to create an instance of PerformanceMetrics
            //instance = new PerformanceMetrics();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PerformanceMetrics
        /// </summary>
        [Fact]
        public void PerformanceMetricsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PerformanceMetrics
            //Assert.IsType<PerformanceMetrics>(instance);
        }


        /// <summary>
        /// Test the property 'CurrentDay'
        /// </summary>
        [Fact]
        public void CurrentDayTest()
        {
            // TODO unit test for the property 'CurrentDay'
        }
        /// <summary>
        /// Test the property 'PreviousDays'
        /// </summary>
        [Fact]
        public void PreviousDaysTest()
        {
            // TODO unit test for the property 'PreviousDays'
        }

    }

}
