/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Agl.Cdr.Energy.Client;
using Agl.Cdr.Energy.Apis;
// uncomment below to import models
//using Agl.Cdr.Energy.Models;

namespace Agl.Cdr.Energy.Test.Api
{
    /// <summary>
    ///  Class for testing EnergyAccountsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EnergyAccountsApiTests : IDisposable
    {
        private EnergyAccountsApi instance;

        public EnergyAccountsApiTests()
        {
            instance = new EnergyAccountsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnergyAccountsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EnergyAccountsApi
            //Assert.IsType<EnergyAccountsApi>(instance);
        }

        /// <summary>
        /// Test GetAccount
        /// </summary>
        [Fact]
        public void GetAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string xV = null;
            //string xMinV = null;
            //string xFapiInteractionId = null;
            //string xFapiAuthDate = null;
            //string xFapiCustomerIpAddress = null;
            //string xCdsClientHeaders = null;
            //var response = instance.GetAccount(accountId, xV, xMinV, xFapiInteractionId, xFapiAuthDate, xFapiCustomerIpAddress, xCdsClientHeaders);
            //Assert.IsType<EnergyAccountDetailResponse>(response);
        }

        /// <summary>
        /// Test GetConcessions
        /// </summary>
        [Fact]
        public void GetConcessionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string xV = null;
            //string xMinV = null;
            //string xFapiInteractionId = null;
            //string xFapiAuthDate = null;
            //string xFapiCustomerIpAddress = null;
            //string xCdsClientHeaders = null;
            //var response = instance.GetConcessions(accountId, xV, xMinV, xFapiInteractionId, xFapiAuthDate, xFapiCustomerIpAddress, xCdsClientHeaders);
            //Assert.IsType<EnergyConcessionsResponse>(response);
        }

        /// <summary>
        /// Test GetPaymentSchedule
        /// </summary>
        [Fact]
        public void GetPaymentScheduleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string xV = null;
            //string xMinV = null;
            //string xFapiInteractionId = null;
            //string xFapiAuthDate = null;
            //string xFapiCustomerIpAddress = null;
            //string xCdsClientHeaders = null;
            //var response = instance.GetPaymentSchedule(accountId, xV, xMinV, xFapiInteractionId, xFapiAuthDate, xFapiCustomerIpAddress, xCdsClientHeaders);
            //Assert.IsType<EnergyPaymentScheduleResponse>(response);
        }

        /// <summary>
        /// Test ListAccounts
        /// </summary>
        [Fact]
        public void ListAccountsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xV = null;
            //decimal? page = null;
            //decimal? pageSize = null;
            //string xMinV = null;
            //string xFapiInteractionId = null;
            //string xFapiAuthDate = null;
            //string xFapiCustomerIpAddress = null;
            //string xCdsClientHeaders = null;
            //var response = instance.ListAccounts(xV, page, pageSize, xMinV, xFapiInteractionId, xFapiAuthDate, xFapiCustomerIpAddress, xCdsClientHeaders);
            //Assert.IsType<EnergyAccountListResponse>(response);
        }
    }
}
