#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/Agl.Cdr.Admin/ && \
    dotnet build src/Agl.Cdr.Admin/ && \
    echo "Now, run the following to start the project: dotnet run -p src/Agl.Cdr.Admin/Agl.Cdr.Admin.csproj --launch-profile web"
