/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Agl.Cdr.Energy.Attributes;
using Agl.Cdr.Energy.Models;

namespace Agl.Cdr.Energy.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class EnergyAccountsApiController : ControllerBase
    { 
        /// <summary>
        /// Get Energy Account Detail
        /// </summary>
        /// <remarks>Obtain detailed information for a specific energy account</remarks>
        /// <param name="accountId">ID of a specific account to obtain data for.  This is a tokenised ID previous obtained from the Account List end point.</param>
        /// <param name="xV">Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers)</param>
        /// <param name="xMinV">Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable.</param>
        /// <param name="xFapiInteractionId">An [RFC4122](https://tools.ietf.org/html/rfc4122) UUID used as a correlation id. If provided, the data holder must play back this value in the x-fapi-interaction-id response header. If not provided a [RFC4122] UUID value is required to be provided in the response header to track the interaction.</param>
        /// <param name="xFapiAuthDate">The time when the customer last logged in to the data recipient. Required for all resource calls (customer present and unattended). Not to be included for unauthenticated calls.</param>
        /// <param name="xFapiCustomerIpAddress">The customer&#39;s original IP address if the customer is currently logged in to the data recipient. The presence of this header indicates that the API is being called in a customer present context. Not to be included for unauthenticated calls.</param>
        /// <param name="xCdsClientHeaders">The customer&#39;s original standard http headers [Base64](#common-field-types) encoded, including the original User Agent header, if the customer is currently logged in to the data recipient. Mandatory for customer present calls.  Not required for unattended or unauthenticated calls.</param>
        /// <response code="200">Successful response</response>
        /// <response code="0">The following error codes MUST be supported:&lt;br/&gt;&lt;ul class&#x3D;\&quot;error-code-list\&quot;&gt;&lt;li&gt;[400 - Invalid Field](#error-400-field-invalid)&lt;/li&gt;&lt;li&gt;[400 - Invalid Version](#error-400-header-invalid-version)&lt;/li&gt;&lt;li&gt;[406 - Unsupported Version](#error-406-header-unsupported-version)&lt;/li&gt;&lt;li&gt;[404 - Unavailable Energy Account](#error-404-unavailable-energy-account)&lt;/li&gt;&lt;li&gt;[404 - Invalid Energy Account](#error-404-invalid-energy-account)&lt;/li&gt;&lt;/ul&gt;</response>
        [HttpGet]
        [Route("/energy/accounts/{accountId}")]
        [ValidateModelState]
        [SwaggerOperation("GetAccount")]
        [SwaggerResponse(statusCode: 200, type: typeof(EnergyAccountDetailResponse), description: "Successful response")]
        [SwaggerResponse(statusCode: 0, type: typeof(ErrorListResponse), description: "The following error codes MUST be supported:&lt;br/&gt;&lt;ul class&#x3D;\&quot;error-code-list\&quot;&gt;&lt;li&gt;[400 - Invalid Field](#error-400-field-invalid)&lt;/li&gt;&lt;li&gt;[400 - Invalid Version](#error-400-header-invalid-version)&lt;/li&gt;&lt;li&gt;[406 - Unsupported Version](#error-406-header-unsupported-version)&lt;/li&gt;&lt;li&gt;[404 - Unavailable Energy Account](#error-404-unavailable-energy-account)&lt;/li&gt;&lt;li&gt;[404 - Invalid Energy Account](#error-404-invalid-energy-account)&lt;/li&gt;&lt;/ul&gt;")]
        public virtual IActionResult GetAccount([FromRoute (Name = "accountId")][Required]string accountId, [FromHeader][Required()]string xV, [FromHeader]string xMinV, [FromHeader]string xFapiInteractionId, [FromHeader]string xFapiAuthDate, [FromHeader]string xFapiCustomerIpAddress, [FromHeader]string xCdsClientHeaders)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(EnergyAccountDetailResponse));
            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(ErrorListResponse));
            string exampleJson = null;
            exampleJson = "{\n  \"meta\" : \"{}\",\n  \"links\" : {\n    \"self\" : \"self\"\n  }\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<EnergyAccountDetailResponse>(exampleJson)
            : default(EnergyAccountDetailResponse);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Get Concessions
        /// </summary>
        /// <remarks>Obtain the details of any concessions or arrangements applied to a specific energy account</remarks>
        /// <param name="accountId">ID of a specific account to obtain data for.  This is a tokenised ID previous obtained from the Account List end point.</param>
        /// <param name="xV">Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers)</param>
        /// <param name="xMinV">Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable.</param>
        /// <param name="xFapiInteractionId">An [RFC4122](https://tools.ietf.org/html/rfc4122) UUID used as a correlation id. If provided, the data holder must play back this value in the x-fapi-interaction-id response header. If not provided a [RFC4122] UUID value is required to be provided in the response header to track the interaction.</param>
        /// <param name="xFapiAuthDate">The time when the customer last logged in to the data recipient. Required for all resource calls (customer present and unattended). Not to be included for unauthenticated calls.</param>
        /// <param name="xFapiCustomerIpAddress">The customer&#39;s original IP address if the customer is currently logged in to the data recipient. The presence of this header indicates that the API is being called in a customer present context. Not to be included for unauthenticated calls.</param>
        /// <param name="xCdsClientHeaders">The customer&#39;s original standard http headers [Base64](#common-field-types) encoded, including the original User Agent header, if the customer is currently logged in to the data recipient. Mandatory for customer present calls.  Not required for unattended or unauthenticated calls.</param>
        /// <response code="200">Successful response</response>
        /// <response code="0">The following error codes MUST be supported:&lt;br/&gt;&lt;ul class&#x3D;\&quot;error-code-list\&quot;&gt;&lt;li&gt;[400 - Invalid Field](#error-400-field-invalid)&lt;/li&gt;&lt;li&gt;[400 - Invalid Version](#error-400-header-invalid-version)&lt;/li&gt;&lt;li&gt;[406 - Unsupported Version](#error-406-header-unsupported-version)&lt;/li&gt;&lt;li&gt;[404 - Unavailable Energy Account](#error-404-unavailable-energy-account)&lt;/li&gt;&lt;li&gt;[404 - Invalid Energy Account](#error-404-invalid-energy-account)&lt;/li&gt;&lt;/ul&gt;</response>
        [HttpGet]
        [Route("/energy/accounts/{accountId}/concessions")]
        [ValidateModelState]
        [SwaggerOperation("GetConcessions")]
        [SwaggerResponse(statusCode: 200, type: typeof(EnergyConcessionsResponse), description: "Successful response")]
        [SwaggerResponse(statusCode: 0, type: typeof(ErrorListResponse), description: "The following error codes MUST be supported:&lt;br/&gt;&lt;ul class&#x3D;\&quot;error-code-list\&quot;&gt;&lt;li&gt;[400 - Invalid Field](#error-400-field-invalid)&lt;/li&gt;&lt;li&gt;[400 - Invalid Version](#error-400-header-invalid-version)&lt;/li&gt;&lt;li&gt;[406 - Unsupported Version](#error-406-header-unsupported-version)&lt;/li&gt;&lt;li&gt;[404 - Unavailable Energy Account](#error-404-unavailable-energy-account)&lt;/li&gt;&lt;li&gt;[404 - Invalid Energy Account](#error-404-invalid-energy-account)&lt;/li&gt;&lt;/ul&gt;")]
        public virtual IActionResult GetConcessions([FromRoute (Name = "accountId")][Required]string accountId, [FromHeader][Required()]string xV, [FromHeader]string xMinV, [FromHeader]string xFapiInteractionId, [FromHeader]string xFapiAuthDate, [FromHeader]string xFapiCustomerIpAddress, [FromHeader]string xCdsClientHeaders)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(EnergyConcessionsResponse));
            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(ErrorListResponse));
            string exampleJson = null;
            exampleJson = "{\n  \"data\" : {\n    \"concessions\" : [ {\n      \"percentageDiscount\" : \"percentageDiscount\",\n      \"additionalInfoUri\" : \"additionalInfoUri\",\n      \"endDate\" : \"endDate\",\n      \"displayName\" : \"displayName\",\n      \"additionalInfo\" : \"additionalInfo\",\n      \"dailyDiscount\" : \"dailyDiscount\",\n      \"monthlyDiscount\" : \"monthlyDiscount\",\n      \"startDate\" : \"startDate\",\n      \"yearlyDiscount\" : \"yearlyDiscount\"\n    }, {\n      \"percentageDiscount\" : \"percentageDiscount\",\n      \"additionalInfoUri\" : \"additionalInfoUri\",\n      \"endDate\" : \"endDate\",\n      \"displayName\" : \"displayName\",\n      \"additionalInfo\" : \"additionalInfo\",\n      \"dailyDiscount\" : \"dailyDiscount\",\n      \"monthlyDiscount\" : \"monthlyDiscount\",\n      \"startDate\" : \"startDate\",\n      \"yearlyDiscount\" : \"yearlyDiscount\"\n    } ]\n  },\n  \"meta\" : \"{}\",\n  \"links\" : {\n    \"self\" : \"self\"\n  }\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<EnergyConcessionsResponse>(exampleJson)
            : default(EnergyConcessionsResponse);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Get Agreed Payment Schedule
        /// </summary>
        /// <remarks>Obtain the agreed payment schedule and details, if any, for a specific energy account</remarks>
        /// <param name="accountId">ID of a specific account to obtain data for.  This is a tokenised ID previous obtained from the Account List end point.</param>
        /// <param name="xV">Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers)</param>
        /// <param name="xMinV">Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable.</param>
        /// <param name="xFapiInteractionId">An [RFC4122](https://tools.ietf.org/html/rfc4122) UUID used as a correlation id. If provided, the data holder must play back this value in the x-fapi-interaction-id response header. If not provided a [RFC4122] UUID value is required to be provided in the response header to track the interaction.</param>
        /// <param name="xFapiAuthDate">The time when the customer last logged in to the data recipient. Required for all resource calls (customer present and unattended). Not to be included for unauthenticated calls.</param>
        /// <param name="xFapiCustomerIpAddress">The customer&#39;s original IP address if the customer is currently logged in to the data recipient. The presence of this header indicates that the API is being called in a customer present context. Not to be included for unauthenticated calls.</param>
        /// <param name="xCdsClientHeaders">The customer&#39;s original standard http headers [Base64](#common-field-types) encoded, including the original User Agent header, if the customer is currently logged in to the data recipient. Mandatory for customer present calls.  Not required for unattended or unauthenticated calls.</param>
        /// <response code="200">Successful response</response>
        /// <response code="0">The following error codes MUST be supported:&lt;br/&gt;&lt;ul class&#x3D;\&quot;error-code-list\&quot;&gt;&lt;li&gt;[400 - Invalid Field](#error-400-field-invalid)&lt;/li&gt;&lt;li&gt;[400 - Invalid Version](#error-400-header-invalid-version)&lt;/li&gt;&lt;li&gt;[406 - Unsupported Version](#error-406-header-unsupported-version)&lt;/li&gt;&lt;li&gt;[404 - Unavailable Energy Account](#error-404-unavailable-energy-account)&lt;/li&gt;&lt;li&gt;[404 - Invalid Energy Account](#error-404-invalid-energy-account)&lt;/li&gt;&lt;/ul&gt;</response>
        [HttpGet]
        [Route("/energy/accounts/{accountId}/payment-schedule")]
        [ValidateModelState]
        [SwaggerOperation("GetPaymentSchedule")]
        [SwaggerResponse(statusCode: 200, type: typeof(EnergyPaymentScheduleResponse), description: "Successful response")]
        [SwaggerResponse(statusCode: 0, type: typeof(ErrorListResponse), description: "The following error codes MUST be supported:&lt;br/&gt;&lt;ul class&#x3D;\&quot;error-code-list\&quot;&gt;&lt;li&gt;[400 - Invalid Field](#error-400-field-invalid)&lt;/li&gt;&lt;li&gt;[400 - Invalid Version](#error-400-header-invalid-version)&lt;/li&gt;&lt;li&gt;[406 - Unsupported Version](#error-406-header-unsupported-version)&lt;/li&gt;&lt;li&gt;[404 - Unavailable Energy Account](#error-404-unavailable-energy-account)&lt;/li&gt;&lt;li&gt;[404 - Invalid Energy Account](#error-404-invalid-energy-account)&lt;/li&gt;&lt;/ul&gt;")]
        public virtual IActionResult GetPaymentSchedule([FromRoute (Name = "accountId")][Required]string accountId, [FromHeader][Required()]string xV, [FromHeader]string xMinV, [FromHeader]string xFapiInteractionId, [FromHeader]string xFapiAuthDate, [FromHeader]string xFapiCustomerIpAddress, [FromHeader]string xCdsClientHeaders)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(EnergyPaymentScheduleResponse));
            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(ErrorListResponse));
            string exampleJson = null;
            exampleJson = "{\n  \"data\" : {\n    \"manualPayment\" : {\n      \"billFrequency\" : \"billFrequency\"\n    },\n    \"amount\" : \"amount\",\n    \"cardDebit\" : {\n      \"calculationType\" : \"STATIC\",\n      \"cardScheme\" : \"VISA\",\n      \"paymentFrequency\" : \"paymentFrequency\"\n    },\n    \"directDebit\" : {\n      \"bsb\" : \"bsb\",\n      \"calculationType\" : \"STATIC\",\n      \"accountNumber\" : \"accountNumber\",\n      \"paymentFrequency\" : \"paymentFrequency\",\n      \"isTokenised\" : \"isTokenised\"\n    },\n    \"paymentScheduleUType\" : \"cardDebit\"\n  },\n  \"meta\" : \"{}\",\n  \"links\" : {\n    \"self\" : \"self\"\n  }\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<EnergyPaymentScheduleResponse>(exampleJson)
            : default(EnergyPaymentScheduleResponse);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Get Energy Accounts
        /// </summary>
        /// <remarks>Obtain the list of energy accounts available under the authorised consent</remarks>
        /// <param name="xV">Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers)</param>
        /// <param name="page">Page of results to request (standard pagination)</param>
        /// <param name="pageSize">Page size to request.  Default is 25 (standard pagination)</param>
        /// <param name="xMinV">Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable.</param>
        /// <param name="xFapiInteractionId">An [RFC4122](https://tools.ietf.org/html/rfc4122) UUID used as a correlation id. If provided, the data holder must play back this value in the x-fapi-interaction-id response header. If not provided a [RFC4122] UUID value is required to be provided in the response header to track the interaction.</param>
        /// <param name="xFapiAuthDate">The time when the customer last logged in to the data recipient. Required for all resource calls (customer present and unattended). Not to be included for unauthenticated calls.</param>
        /// <param name="xFapiCustomerIpAddress">The customer&#39;s original IP address if the customer is currently logged in to the data recipient. The presence of this header indicates that the API is being called in a customer present context. Not to be included for unauthenticated calls.</param>
        /// <param name="xCdsClientHeaders">The customer&#39;s original standard http headers [Base64](#common-field-types) encoded, including the original User Agent header, if the customer is currently logged in to the data recipient. Mandatory for customer present calls.  Not required for unattended or unauthenticated calls.</param>
        /// <response code="200">Successful response</response>
        /// <response code="0">The following error codes MUST be supported:&lt;br/&gt;&lt;ul class&#x3D;\&quot;error-code-list\&quot;&gt;&lt;li&gt;[400 - Invalid Field](#error-400-field-invalid)&lt;/li&gt;&lt;li&gt;[400 - Invalid Page Size](#error-400-field-invalid-page-size)&lt;/li&gt;&lt;li&gt;[400 - Invalid Version](#error-400-header-invalid-version)&lt;/li&gt;&lt;li&gt;[406 - Unsupported Version](#error-406-header-unsupported-version)&lt;/li&gt;&lt;li&gt;[422 - Invalid Page](#error-422-field-invalid-page)&lt;/li&gt;&lt;/ul&gt;</response>
        [HttpGet]
        [Route("/energy/accounts")]
        [ValidateModelState]
        [SwaggerOperation("ListAccounts")]
        [SwaggerResponse(statusCode: 200, type: typeof(EnergyAccountListResponse), description: "Successful response")]
        [SwaggerResponse(statusCode: 0, type: typeof(ErrorListResponse), description: "The following error codes MUST be supported:&lt;br/&gt;&lt;ul class&#x3D;\&quot;error-code-list\&quot;&gt;&lt;li&gt;[400 - Invalid Field](#error-400-field-invalid)&lt;/li&gt;&lt;li&gt;[400 - Invalid Page Size](#error-400-field-invalid-page-size)&lt;/li&gt;&lt;li&gt;[400 - Invalid Version](#error-400-header-invalid-version)&lt;/li&gt;&lt;li&gt;[406 - Unsupported Version](#error-406-header-unsupported-version)&lt;/li&gt;&lt;li&gt;[422 - Invalid Page](#error-422-field-invalid-page)&lt;/li&gt;&lt;/ul&gt;")]
        public virtual IActionResult ListAccounts([FromHeader][Required()]string xV, [FromQuery (Name = "page")]decimal? page, [FromQuery (Name = "page-size")]decimal? pageSize, [FromHeader]string xMinV, [FromHeader]string xFapiInteractionId, [FromHeader]string xFapiAuthDate, [FromHeader]string xFapiCustomerIpAddress, [FromHeader]string xCdsClientHeaders)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(EnergyAccountListResponse));
            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(ErrorListResponse));
            string exampleJson = null;
            exampleJson = "{\n  \"data\" : {\n    \"accounts\" : [ null, null ]\n  },\n  \"meta\" : {\n    \"totalRecords\" : 0,\n    \"totalPages\" : 6\n  },\n  \"links\" : {\n    \"next\" : \"next\",\n    \"last\" : \"last\",\n    \"prev\" : \"prev\",\n    \"self\" : \"self\",\n    \"first\" : \"first\"\n  }\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<EnergyAccountListResponse>(exampleJson)
            : default(EnergyAccountListResponse);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
