/*
 * CDR Common API
 *
 * Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right
 *
 * The version of the OpenAPI document: 1.15.0
 * Contact: contact@consumerdatastandards.gov.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Common.Apis;
using Agl.Cdr.Common.Models;
using Agl.Cdr.Common.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Common.Test.Model
{
    /// <summary>
    ///  Class for testing CommonPhysicalAddressWithPurpose1AllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommonPhysicalAddressWithPurpose1AllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommonPhysicalAddressWithPurpose1AllOf
        //private CommonPhysicalAddressWithPurpose1AllOf instance;

        public CommonPhysicalAddressWithPurpose1AllOfTests()
        {
            // TODO uncomment below to create an instance of CommonPhysicalAddressWithPurpose1AllOf
            //instance = new CommonPhysicalAddressWithPurpose1AllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommonPhysicalAddressWithPurpose1AllOf
        /// </summary>
        [Fact]
        public void CommonPhysicalAddressWithPurpose1AllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommonPhysicalAddressWithPurpose1AllOf
            //Assert.IsType<CommonPhysicalAddressWithPurpose1AllOf>(instance);
        }


        /// <summary>
        /// Test the property 'Purpose'
        /// </summary>
        [Fact]
        public void PurposeTest()
        {
            // TODO unit test for the property 'Purpose'
        }

    }

}
