/*
 * CDR Common API
 *
 * Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right
 *
 * The version of the OpenAPI document: 1.15.0
 * Contact: contact@consumerdatastandards.gov.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Common.Apis;
using Agl.Cdr.Common.Models;
using Agl.Cdr.Common.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Common.Test.Model
{
    /// <summary>
    ///  Class for testing ResponseCommonDiscoveryStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseCommonDiscoveryStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseCommonDiscoveryStatus
        //private ResponseCommonDiscoveryStatus instance;

        public ResponseCommonDiscoveryStatusTests()
        {
            // TODO uncomment below to create an instance of ResponseCommonDiscoveryStatus
            //instance = new ResponseCommonDiscoveryStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseCommonDiscoveryStatus
        /// </summary>
        [Fact]
        public void ResponseCommonDiscoveryStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResponseCommonDiscoveryStatus
            //Assert.IsType<ResponseCommonDiscoveryStatus>(instance);
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }

    }

}
