/*
 * CDR Common API
 *
 * Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right
 *
 * The version of the OpenAPI document: 1.15.0
 * Contact: contact@consumerdatastandards.gov.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Common.Apis;
using Agl.Cdr.Common.Models;
using Agl.Cdr.Common.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Common.Test.Model
{
    /// <summary>
    ///  Class for testing ResponseCommonCustomerData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseCommonCustomerDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseCommonCustomerData
        //private ResponseCommonCustomerData instance;

        public ResponseCommonCustomerDataTests()
        {
            // TODO uncomment below to create an instance of ResponseCommonCustomerData
            //instance = new ResponseCommonCustomerData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseCommonCustomerData
        /// </summary>
        [Fact]
        public void ResponseCommonCustomerDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResponseCommonCustomerData
            //Assert.IsType<ResponseCommonCustomerData>(instance);
        }


        /// <summary>
        /// Test the property 'CustomerUType'
        /// </summary>
        [Fact]
        public void CustomerUTypeTest()
        {
            // TODO unit test for the property 'CustomerUType'
        }
        /// <summary>
        /// Test the property 'Person'
        /// </summary>
        [Fact]
        public void PersonTest()
        {
            // TODO unit test for the property 'Person'
        }
        /// <summary>
        /// Test the property 'Organisation'
        /// </summary>
        [Fact]
        public void OrganisationTest()
        {
            // TODO unit test for the property 'Organisation'
        }

    }

}
