// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace Agl.Cdr.Energy
{
    /// <summary> The measurement unit of rate. Assumed to be KWH if absent. </summary>
    public readonly partial struct EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit : IEquatable<EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit>
    {
        private readonly string _value;

        /// <summary> Determines if two <see cref="EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit"/> values are the same. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string KWHValue = "KWH";
        private const string KVAValue = "KVA";
        private const string KvarValue = "KVAR";
        private const string KvarhValue = "KVARH";
        private const string KWValue = "KW";
        private const string DaysValue = "DAYS";
        private const string MeterValue = "METER";
        private const string MonthValue = "MONTH";

        /// <summary> KWH. </summary>
        public static EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit KWH { get; } = new EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit(KWHValue);
        /// <summary> KVA. </summary>
        public static EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit KVA { get; } = new EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit(KVAValue);
        /// <summary> KVAR. </summary>
        public static EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit Kvar { get; } = new EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit(KvarValue);
        /// <summary> KVARH. </summary>
        public static EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit Kvarh { get; } = new EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit(KvarhValue);
        /// <summary> KW. </summary>
        public static EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit KW { get; } = new EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit(KWValue);
        /// <summary> DAYS. </summary>
        public static EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit Days { get; } = new EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit(DaysValue);
        /// <summary> METER. </summary>
        public static EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit Meter { get; } = new EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit(MeterValue);
        /// <summary> MONTH. </summary>
        public static EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit Month { get; } = new EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit(MonthValue);
        /// <summary> Determines if two <see cref="EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit"/> values are the same. </summary>
        public static bool operator ==(EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit left, EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit right) => left.Equals(right);
        /// <summary> Determines if two <see cref="EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit"/> values are not the same. </summary>
        public static bool operator !=(EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit left, EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit"/>. </summary>
        public static implicit operator EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit(string value) => new EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit other && Equals(other);
        /// <inheritdoc />
        public bool Equals(EnergyPlanTariffPeriodItemSingleRateRatesItemMeasureUnit other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
