// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Agl.Cdr.Energy.Models
{
    /// <summary> The EnergyInvoiceListResponseData. </summary>
    public partial class EnergyInvoiceListResponseData
    {
        /// <summary> Initializes a new instance of EnergyInvoiceListResponseData. </summary>
        /// <param name="invoices"> Array of invoices sorted by date in descending order. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="invoices"/> is null. </exception>
        internal EnergyInvoiceListResponseData(List<EnergyInvoice> invoices)
        {
            if (invoices == null)
            {
                throw new ArgumentNullException(nameof(invoices));
            }

            Invoices = invoices;
        }

        /// <summary> Initializes a new instance of EnergyInvoiceListResponseData. </summary>
        /// <param name="invoices"> Array of invoices sorted by date in descending order. </param>
        internal EnergyInvoiceListResponseData(IReadOnlyList<EnergyInvoice> invoices)
        {
            Invoices = invoices;
        }

        /// <summary> Array of invoices sorted by date in descending order. </summary>
        public IReadOnlyList<EnergyInvoice> Invoices { get; }
    }
}
