// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Agl.Cdr.Energy.Models
{
    /// <summary> The EnergyBillingListResponseData. </summary>
    public partial class EnergyBillingListResponseData
    {
        /// <summary> Initializes a new instance of EnergyBillingListResponseData. </summary>
        /// <param name="transactions"> Array of transactions sorted by date and time in descending order. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="transactions"/> is null. </exception>
        internal EnergyBillingListResponseData(List<EnergyBillingTransaction> transactions)
        {
            if (transactions == null)
            {
                throw new ArgumentNullException(nameof(transactions));
            }

            Transactions = transactions;
        }

        /// <summary> Initializes a new instance of EnergyBillingListResponseData. </summary>
        /// <param name="transactions"> Array of transactions sorted by date and time in descending order. </param>
        internal EnergyBillingListResponseData(IReadOnlyList<EnergyBillingTransaction> transactions)
        {
            Transactions = transactions;
        }

        /// <summary> Array of transactions sorted by date and time in descending order. </summary>
        public IReadOnlyList<EnergyBillingTransaction> Transactions { get; }
    }
}
