// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using Agl.Cdr.Energy;

namespace Agl.Cdr.Energy.Models
{
    /// <summary> Mandatory if readUType is set to basicRead. </summary>
    public partial class EnergyUsageReadBasicRead
    {
        /// <summary> Initializes a new instance of EnergyUsageReadBasicRead. </summary>
        /// <param name="value"> Meter read value.  If positive then it means consumption, if negative it means export. </param>
        internal EnergyUsageReadBasicRead(float value)
        {
            Value = value;
        }

        /// <summary> Initializes a new instance of EnergyUsageReadBasicRead. </summary>
        /// <param name="quality"> The quality of the read taken.  If absent then assumed to be ACTUAL. </param>
        /// <param name="value"> Meter read value.  If positive then it means consumption, if negative it means export. </param>
        internal EnergyUsageReadBasicRead(EnergyUsageReadBasicReadQuality? quality, float value)
        {
            Quality = quality;
            Value = value;
        }

        /// <summary> The quality of the read taken.  If absent then assumed to be ACTUAL. </summary>
        public EnergyUsageReadBasicReadQuality? Quality { get; }
        /// <summary> Meter read value.  If positive then it means consumption, if negative it means export. </summary>
        public float Value { get; }
    }
}
