// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using Agl.Cdr.Energy;

namespace Agl.Cdr.Energy.Models
{
    /// <summary> The EnergyDerRecordDerDevices. </summary>
    public partial class EnergyDerRecordDerDevices
    {
        /// <summary> Initializes a new instance of EnergyDerRecordDerDevices. </summary>
        /// <param name="deviceIdentifier"> Unique identifier for a single DER device or a group of DER devices with the same attributes. Does not align with CDR ID permanence standards. </param>
        /// <param name="count"> Number of devices in the group of DER devices. </param>
        /// <param name="type"> Used to indicate the primary technology used in the DER device. </param>
        /// <param name="nominalRatedCapacity"> Maximum output in kVA that is listed in the product specification by the manufacturer. This refers to the capacity of each unit within the device group. </param>
        internal EnergyDerRecordDerDevices(float deviceIdentifier, float count, EnergyDerRecordDerDevicesType type, float nominalRatedCapacity)
        {
            DeviceIdentifier = deviceIdentifier;
            Count = count;
            Type = type;
            NominalRatedCapacity = nominalRatedCapacity;
        }

        /// <summary> Initializes a new instance of EnergyDerRecordDerDevices. </summary>
        /// <param name="deviceIdentifier"> Unique identifier for a single DER device or a group of DER devices with the same attributes. Does not align with CDR ID permanence standards. </param>
        /// <param name="count"> Number of devices in the group of DER devices. </param>
        /// <param name="manufacturer"> The name of the device manufacturer. If absent then assumed to be “unknown”. </param>
        /// <param name="modelNumber"> The model number of the device. If absent then assumed to be “unknown”. </param>
        /// <param name="status"> Code used to indicate the status of the device. This will be used to identify if an inverter is active or inactive or decommissioned. </param>
        /// <param name="type"> Used to indicate the primary technology used in the DER device. </param>
        /// <param name="subtype"> Used to indicate the primary technology used in the DER device. This field is also used to record for example the battery chemistry, or the type of PV panel. It is also used to record if a battery is contained in an electric vehicle connected in a vehicle-to-grid arrangement. If absent then assumed to be “other”. </param>
        /// <param name="nominalRatedCapacity"> Maximum output in kVA that is listed in the product specification by the manufacturer. This refers to the capacity of each unit within the device group. </param>
        /// <param name="nominalStorageCapacity"> Maximum storage capacity in kVAh. This refers to the capacity of each storage module within the device group. Mandatory if type is equal to “STORAGE”. </param>
        internal EnergyDerRecordDerDevices(float deviceIdentifier, float count, string manufacturer, string modelNumber, EnergyDerRecordDerDevicesStatus? status, EnergyDerRecordDerDevicesType type, string subtype, float nominalRatedCapacity, float? nominalStorageCapacity)
        {
            DeviceIdentifier = deviceIdentifier;
            Count = count;
            Manufacturer = manufacturer;
            ModelNumber = modelNumber;
            Status = status;
            Type = type;
            Subtype = subtype;
            NominalRatedCapacity = nominalRatedCapacity;
            NominalStorageCapacity = nominalStorageCapacity;
        }

        /// <summary> Unique identifier for a single DER device or a group of DER devices with the same attributes. Does not align with CDR ID permanence standards. </summary>
        public float DeviceIdentifier { get; }
        /// <summary> Number of devices in the group of DER devices. </summary>
        public float Count { get; }
        /// <summary> The name of the device manufacturer. If absent then assumed to be “unknown”. </summary>
        public string Manufacturer { get; }
        /// <summary> The model number of the device. If absent then assumed to be “unknown”. </summary>
        public string ModelNumber { get; }
        /// <summary> Code used to indicate the status of the device. This will be used to identify if an inverter is active or inactive or decommissioned. </summary>
        public EnergyDerRecordDerDevicesStatus? Status { get; }
        /// <summary> Used to indicate the primary technology used in the DER device. </summary>
        public EnergyDerRecordDerDevicesType Type { get; }
        /// <summary> Used to indicate the primary technology used in the DER device. This field is also used to record for example the battery chemistry, or the type of PV panel. It is also used to record if a battery is contained in an electric vehicle connected in a vehicle-to-grid arrangement. If absent then assumed to be “other”. </summary>
        public string Subtype { get; }
        /// <summary> Maximum output in kVA that is listed in the product specification by the manufacturer. This refers to the capacity of each unit within the device group. </summary>
        public float NominalRatedCapacity { get; }
        /// <summary> Maximum storage capacity in kVAh. This refers to the capacity of each storage module within the device group. Mandatory if type is equal to “STORAGE”. </summary>
        public float? NominalStorageCapacity { get; }
    }
}
