// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using Agl.Cdr.Energy;

namespace Agl.Cdr.Energy.Models
{
    /// <summary> Technical characteristics of the meter. </summary>
    public partial class EnergyServicePointDetailMetersSpecifications
    {
        /// <summary> Initializes a new instance of EnergyServicePointDetailMetersSpecifications. </summary>
        /// <param name="status"> A code to denote the status of the meter. Note the details of enumeration values below: &lt;ul&gt;&lt;li&gt;**CURRENT** -Applies when a meter is current and not disconnected&lt;/li&gt;&lt;li&gt;**DISCONNECTED** - Applies when a meter is present but has been remotely disconnected&lt;/li&gt;&lt;/ul&gt;. </param>
        /// <param name="installationType"> The metering Installation type code indicates whether the metering installation has to be manually read. Note the details of enumeration values below: &lt;ul&gt;&lt;li&gt;**BASIC** - Accumulation Meter – Type 6&lt;/li&gt;&lt;li&gt;**COMMS1** - Interval Meter with communications – Type 1&lt;/li&gt;&lt;li&gt;**COMMS2** - Interval Meter with communications – Type 2&lt;/li&gt;&lt;li&gt;**COMMS3** - Interval Meter with communications – Type 3&lt;/li&gt;&lt;li&gt;**COMMS4** - Interval Meter with communications – Type 4&lt;/li&gt;&lt;li&gt;**COMMS4C** - CT connected metering installation that meets the minimum services specifications&lt;/li&gt;&lt;li&gt;**COMMS4D** - Whole current metering installation that meets the minimum services specifications&lt;/li&gt;&lt;li&gt;**MRAM** - Small customer metering installation – Type 4A&lt;/li&gt;&lt;li&gt;**MRIM** - Manually Read Interval Meter – Type 5&lt;/li&gt;&lt;li&gt;**UMCP** - Unmetered Supply – Type 7&lt;/li&gt;&lt;li&gt;**VICAMI** - A relevant metering installation as defined in clause 9.9C of the NER&lt;/li&gt;&lt;li&gt;**NCONUML** - Non-contestable unmeter load - Introduced as part of Global Settlement&lt;/li&gt;&lt;/ul&gt;. </param>
        internal EnergyServicePointDetailMetersSpecifications(EnergyServicePointDetailMetersSpecificationsStatus status, EnergyServicePointDetailMetersSpecificationsInstallationType installationType)
        {
            Status = status;
            InstallationType = installationType;
        }

        /// <summary> Initializes a new instance of EnergyServicePointDetailMetersSpecifications. </summary>
        /// <param name="status"> A code to denote the status of the meter. Note the details of enumeration values below: &lt;ul&gt;&lt;li&gt;**CURRENT** -Applies when a meter is current and not disconnected&lt;/li&gt;&lt;li&gt;**DISCONNECTED** - Applies when a meter is present but has been remotely disconnected&lt;/li&gt;&lt;/ul&gt;. </param>
        /// <param name="installationType"> The metering Installation type code indicates whether the metering installation has to be manually read. Note the details of enumeration values below: &lt;ul&gt;&lt;li&gt;**BASIC** - Accumulation Meter – Type 6&lt;/li&gt;&lt;li&gt;**COMMS1** - Interval Meter with communications – Type 1&lt;/li&gt;&lt;li&gt;**COMMS2** - Interval Meter with communications – Type 2&lt;/li&gt;&lt;li&gt;**COMMS3** - Interval Meter with communications – Type 3&lt;/li&gt;&lt;li&gt;**COMMS4** - Interval Meter with communications – Type 4&lt;/li&gt;&lt;li&gt;**COMMS4C** - CT connected metering installation that meets the minimum services specifications&lt;/li&gt;&lt;li&gt;**COMMS4D** - Whole current metering installation that meets the minimum services specifications&lt;/li&gt;&lt;li&gt;**MRAM** - Small customer metering installation – Type 4A&lt;/li&gt;&lt;li&gt;**MRIM** - Manually Read Interval Meter – Type 5&lt;/li&gt;&lt;li&gt;**UMCP** - Unmetered Supply – Type 7&lt;/li&gt;&lt;li&gt;**VICAMI** - A relevant metering installation as defined in clause 9.9C of the NER&lt;/li&gt;&lt;li&gt;**NCONUML** - Non-contestable unmeter load - Introduced as part of Global Settlement&lt;/li&gt;&lt;/ul&gt;. </param>
        /// <param name="manufacturer"> Free text field to identify the manufacturer of the installed meter. </param>
        /// <param name="model"> Free text field to identify the meter manufacturer’s designation for the meter model. </param>
        /// <param name="readType"> Code to denote the method and frequency of Meter Reading. The value is formatted as follows: &lt;ul&gt;&lt;li&gt;First Character = Remote (R) or Manual (M)&lt;/li&gt;&lt;li&gt;Second Character = Mode: T = telephone W = wireless P = powerline I = infra-red G = galvanic V = visual &lt;/li&gt;&lt;li&gt;Third Character = Frequency of Scheduled Meter Readings: 1 = Twelve times per year 2 = Six times per year 3 = Four times per year D = Daily or weekly&lt;/li&gt;&lt;li&gt;Optional Fourth Character = to identify what interval length the meter is capable of reading. This includes five, 15 and 30 minute granularity as the following: A – 5 minute B – 15 minute C – 30 minute D – Cannot convert to 5 minute (i.e. due to metering installation de-energised) M - Manually Read Accumulation Meter&lt;/li&gt;&lt;/ul&gt; For example, &lt;ul&gt;&lt;li&gt;MV3 = Manual, Visual, Quarterly&lt;/li&gt; &lt;li&gt;MV3M = Manual, Visual, Quarterly, Manually Read Accumulation Meter&lt;/li&gt; &lt;li&gt;RWDC = Remote, Wireless, Daily, 30 minutes interval&lt;/li&gt;&lt;/ul&gt;. </param>
        /// <param name="nextScheduledReadDate"> This date is the next scheduled meter read date (NSRD) if a manual Meter Reading is required. </param>
        internal EnergyServicePointDetailMetersSpecifications(EnergyServicePointDetailMetersSpecificationsStatus status, EnergyServicePointDetailMetersSpecificationsInstallationType installationType, string manufacturer, string model, string readType, string nextScheduledReadDate)
        {
            Status = status;
            InstallationType = installationType;
            Manufacturer = manufacturer;
            Model = model;
            ReadType = readType;
            NextScheduledReadDate = nextScheduledReadDate;
        }

        /// <summary> A code to denote the status of the meter. Note the details of enumeration values below: &lt;ul&gt;&lt;li&gt;**CURRENT** -Applies when a meter is current and not disconnected&lt;/li&gt;&lt;li&gt;**DISCONNECTED** - Applies when a meter is present but has been remotely disconnected&lt;/li&gt;&lt;/ul&gt;. </summary>
        public EnergyServicePointDetailMetersSpecificationsStatus Status { get; }
        /// <summary> The metering Installation type code indicates whether the metering installation has to be manually read. Note the details of enumeration values below: &lt;ul&gt;&lt;li&gt;**BASIC** - Accumulation Meter – Type 6&lt;/li&gt;&lt;li&gt;**COMMS1** - Interval Meter with communications – Type 1&lt;/li&gt;&lt;li&gt;**COMMS2** - Interval Meter with communications – Type 2&lt;/li&gt;&lt;li&gt;**COMMS3** - Interval Meter with communications – Type 3&lt;/li&gt;&lt;li&gt;**COMMS4** - Interval Meter with communications – Type 4&lt;/li&gt;&lt;li&gt;**COMMS4C** - CT connected metering installation that meets the minimum services specifications&lt;/li&gt;&lt;li&gt;**COMMS4D** - Whole current metering installation that meets the minimum services specifications&lt;/li&gt;&lt;li&gt;**MRAM** - Small customer metering installation – Type 4A&lt;/li&gt;&lt;li&gt;**MRIM** - Manually Read Interval Meter – Type 5&lt;/li&gt;&lt;li&gt;**UMCP** - Unmetered Supply – Type 7&lt;/li&gt;&lt;li&gt;**VICAMI** - A relevant metering installation as defined in clause 9.9C of the NER&lt;/li&gt;&lt;li&gt;**NCONUML** - Non-contestable unmeter load - Introduced as part of Global Settlement&lt;/li&gt;&lt;/ul&gt;. </summary>
        public EnergyServicePointDetailMetersSpecificationsInstallationType InstallationType { get; }
        /// <summary> Free text field to identify the manufacturer of the installed meter. </summary>
        public string Manufacturer { get; }
        /// <summary> Free text field to identify the meter manufacturer’s designation for the meter model. </summary>
        public string Model { get; }
        /// <summary> Code to denote the method and frequency of Meter Reading. The value is formatted as follows: &lt;ul&gt;&lt;li&gt;First Character = Remote (R) or Manual (M)&lt;/li&gt;&lt;li&gt;Second Character = Mode: T = telephone W = wireless P = powerline I = infra-red G = galvanic V = visual &lt;/li&gt;&lt;li&gt;Third Character = Frequency of Scheduled Meter Readings: 1 = Twelve times per year 2 = Six times per year 3 = Four times per year D = Daily or weekly&lt;/li&gt;&lt;li&gt;Optional Fourth Character = to identify what interval length the meter is capable of reading. This includes five, 15 and 30 minute granularity as the following: A – 5 minute B – 15 minute C – 30 minute D – Cannot convert to 5 minute (i.e. due to metering installation de-energised) M - Manually Read Accumulation Meter&lt;/li&gt;&lt;/ul&gt; For example, &lt;ul&gt;&lt;li&gt;MV3 = Manual, Visual, Quarterly&lt;/li&gt; &lt;li&gt;MV3M = Manual, Visual, Quarterly, Manually Read Accumulation Meter&lt;/li&gt; &lt;li&gt;RWDC = Remote, Wireless, Daily, 30 minutes interval&lt;/li&gt;&lt;/ul&gt;. </summary>
        public string ReadType { get; }
        /// <summary> This date is the next scheduled meter read date (NSRD) if a manual Meter Reading is required. </summary>
        public string NextScheduledReadDate { get; }
    }
}
