// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace Agl.Cdr.Energy
{
    /// <summary> The classification of the service point as defined in MSATS procedures. </summary>
    public readonly partial struct EnergyServicePointClassification : IEquatable<EnergyServicePointClassification>
    {
        private readonly string _value;

        /// <summary> Determines if two <see cref="EnergyServicePointClassification"/> values are the same. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public EnergyServicePointClassification(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string ExternalProfileValue = "EXTERNAL_PROFILE";
        private const string GeneratorValue = "GENERATOR";
        private const string LargeValue = "LARGE";
        private const string SmallValue = "SMALL";
        private const string WholesaleValue = "WHOLESALE";
        private const string NONContestUnmeteredLoadValue = "NON_CONTEST_UNMETERED_LOAD";
        private const string NONRegisteredEmbeddedGeneratorValue = "NON_REGISTERED_EMBEDDED_GENERATOR";
        private const string DistributionWholesaleValue = "DISTRIBUTION_WHOLESALE";

        /// <summary> EXTERNAL_PROFILE. </summary>
        public static EnergyServicePointClassification ExternalProfile { get; } = new EnergyServicePointClassification(ExternalProfileValue);
        /// <summary> GENERATOR. </summary>
        public static EnergyServicePointClassification Generator { get; } = new EnergyServicePointClassification(GeneratorValue);
        /// <summary> LARGE. </summary>
        public static EnergyServicePointClassification Large { get; } = new EnergyServicePointClassification(LargeValue);
        /// <summary> SMALL. </summary>
        public static EnergyServicePointClassification Small { get; } = new EnergyServicePointClassification(SmallValue);
        /// <summary> WHOLESALE. </summary>
        public static EnergyServicePointClassification Wholesale { get; } = new EnergyServicePointClassification(WholesaleValue);
        /// <summary> NON_CONTEST_UNMETERED_LOAD. </summary>
        public static EnergyServicePointClassification NONContestUnmeteredLoad { get; } = new EnergyServicePointClassification(NONContestUnmeteredLoadValue);
        /// <summary> NON_REGISTERED_EMBEDDED_GENERATOR. </summary>
        public static EnergyServicePointClassification NONRegisteredEmbeddedGenerator { get; } = new EnergyServicePointClassification(NONRegisteredEmbeddedGeneratorValue);
        /// <summary> DISTRIBUTION_WHOLESALE. </summary>
        public static EnergyServicePointClassification DistributionWholesale { get; } = new EnergyServicePointClassification(DistributionWholesaleValue);
        /// <summary> Determines if two <see cref="EnergyServicePointClassification"/> values are the same. </summary>
        public static bool operator ==(EnergyServicePointClassification left, EnergyServicePointClassification right) => left.Equals(right);
        /// <summary> Determines if two <see cref="EnergyServicePointClassification"/> values are not the same. </summary>
        public static bool operator !=(EnergyServicePointClassification left, EnergyServicePointClassification right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="EnergyServicePointClassification"/>. </summary>
        public static implicit operator EnergyServicePointClassification(string value) => new EnergyServicePointClassification(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is EnergyServicePointClassification other && Equals(other);
        /// <inheritdoc />
        public bool Equals(EnergyServicePointClassification other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
