// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Agl.Cdr.Energy;

namespace Agl.Cdr.Energy.Models
{
    /// <summary> The EnergyBillingPaymentTransaction. </summary>
    public partial class EnergyBillingPaymentTransaction
    {
        /// <summary> Initializes a new instance of EnergyBillingPaymentTransaction. </summary>
        /// <param name="amount"> The amount paid. </param>
        /// <param name="method"> The method of payment. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="amount"/> is null. </exception>
        internal EnergyBillingPaymentTransaction(string amount, EnergyBillingPaymentTransactionMethod method)
        {
            if (amount == null)
            {
                throw new ArgumentNullException(nameof(amount));
            }

            Amount = amount;
            Method = method;
        }

        /// <summary> The amount paid. </summary>
        public string Amount { get; }
        /// <summary> The method of payment. </summary>
        public EnergyBillingPaymentTransactionMethod Method { get; }
    }
}
