// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace Agl.Cdr.Energy
{
    /// <summary> The type of address object present. </summary>
    public readonly partial struct EnergyServicePointDetailLocationAddressUType : IEquatable<EnergyServicePointDetailLocationAddressUType>
    {
        private readonly string _value;

        /// <summary> Determines if two <see cref="EnergyServicePointDetailLocationAddressUType"/> values are the same. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public EnergyServicePointDetailLocationAddressUType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string SimpleValue = "simple";
        private const string PafValue = "paf";

        /// <summary> simple. </summary>
        public static EnergyServicePointDetailLocationAddressUType Simple { get; } = new EnergyServicePointDetailLocationAddressUType(SimpleValue);
        /// <summary> paf. </summary>
        public static EnergyServicePointDetailLocationAddressUType Paf { get; } = new EnergyServicePointDetailLocationAddressUType(PafValue);
        /// <summary> Determines if two <see cref="EnergyServicePointDetailLocationAddressUType"/> values are the same. </summary>
        public static bool operator ==(EnergyServicePointDetailLocationAddressUType left, EnergyServicePointDetailLocationAddressUType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="EnergyServicePointDetailLocationAddressUType"/> values are not the same. </summary>
        public static bool operator !=(EnergyServicePointDetailLocationAddressUType left, EnergyServicePointDetailLocationAddressUType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="EnergyServicePointDetailLocationAddressUType"/>. </summary>
        public static implicit operator EnergyServicePointDetailLocationAddressUType(string value) => new EnergyServicePointDetailLocationAddressUType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is EnergyServicePointDetailLocationAddressUType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(EnergyServicePointDetailLocationAddressUType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
