// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Agl.Cdr.Energy.Models
{
    /// <summary> Object that contains links to additional information on specific topics. </summary>
    public partial class EnergyPlanAdditionalInformation
    {
        /// <summary> Initializes a new instance of EnergyPlanAdditionalInformation. </summary>
        internal EnergyPlanAdditionalInformation()
        {
        }

        /// <summary> Initializes a new instance of EnergyPlanAdditionalInformation. </summary>
        /// <param name="overviewUri"> A link to a general overview of the plan. </param>
        /// <param name="termsUri"> A link to terms and conditions for the plan. </param>
        /// <param name="eligibilityUri"> A link to detail on eligibility criteria for the plan. </param>
        /// <param name="pricingUri"> A link to detail on pricing for the plan. </param>
        /// <param name="bundleUri"> A link to detail on bundles that this plan can be a part of. </param>
        internal EnergyPlanAdditionalInformation(string overviewUri, string termsUri, string eligibilityUri, string pricingUri, string bundleUri)
        {
            OverviewUri = overviewUri;
            TermsUri = termsUri;
            EligibilityUri = eligibilityUri;
            PricingUri = pricingUri;
            BundleUri = bundleUri;
        }

        /// <summary> A link to a general overview of the plan. </summary>
        public string OverviewUri { get; }
        /// <summary> A link to terms and conditions for the plan. </summary>
        public string TermsUri { get; }
        /// <summary> A link to detail on eligibility criteria for the plan. </summary>
        public string EligibilityUri { get; }
        /// <summary> A link to detail on pricing for the plan. </summary>
        public string PricingUri { get; }
        /// <summary> A link to detail on bundles that this plan can be a part of. </summary>
        public string BundleUri { get; }
    }
}
