/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Energy.Apis;
using Agl.Cdr.Energy.Models;
using Agl.Cdr.Energy.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Energy.Test.Model
{
    /// <summary>
    ///  Class for testing EnergyPaymentScheduleCardDebit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnergyPaymentScheduleCardDebitTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnergyPaymentScheduleCardDebit
        //private EnergyPaymentScheduleCardDebit instance;

        public EnergyPaymentScheduleCardDebitTests()
        {
            // TODO uncomment below to create an instance of EnergyPaymentScheduleCardDebit
            //instance = new EnergyPaymentScheduleCardDebit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnergyPaymentScheduleCardDebit
        /// </summary>
        [Fact]
        public void EnergyPaymentScheduleCardDebitInstanceTest()
        {
            // TODO uncomment below to test "IsType" EnergyPaymentScheduleCardDebit
            //Assert.IsType<EnergyPaymentScheduleCardDebit>(instance);
        }


        /// <summary>
        /// Test the property 'CardScheme'
        /// </summary>
        [Fact]
        public void CardSchemeTest()
        {
            // TODO unit test for the property 'CardScheme'
        }
        /// <summary>
        /// Test the property 'PaymentFrequency'
        /// </summary>
        [Fact]
        public void PaymentFrequencyTest()
        {
            // TODO unit test for the property 'PaymentFrequency'
        }
        /// <summary>
        /// Test the property 'CalculationType'
        /// </summary>
        [Fact]
        public void CalculationTypeTest()
        {
            // TODO unit test for the property 'CalculationType'
        }

    }

}
