/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Energy.Apis;
using Agl.Cdr.Energy.Models;
using Agl.Cdr.Energy.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Energy.Test.Model
{
    /// <summary>
    ///  Class for testing EnergyUsageRead
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnergyUsageReadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnergyUsageRead
        //private EnergyUsageRead instance;

        public EnergyUsageReadTests()
        {
            // TODO uncomment below to create an instance of EnergyUsageRead
            //instance = new EnergyUsageRead();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnergyUsageRead
        /// </summary>
        [Fact]
        public void EnergyUsageReadInstanceTest()
        {
            // TODO uncomment below to test "IsType" EnergyUsageRead
            //Assert.IsType<EnergyUsageRead>(instance);
        }


        /// <summary>
        /// Test the property 'ServicePointId'
        /// </summary>
        [Fact]
        public void ServicePointIdTest()
        {
            // TODO unit test for the property 'ServicePointId'
        }
        /// <summary>
        /// Test the property 'RegisterId'
        /// </summary>
        [Fact]
        public void RegisterIdTest()
        {
            // TODO unit test for the property 'RegisterId'
        }
        /// <summary>
        /// Test the property 'RegisterSuffix'
        /// </summary>
        [Fact]
        public void RegisterSuffixTest()
        {
            // TODO unit test for the property 'RegisterSuffix'
        }
        /// <summary>
        /// Test the property 'MeterID'
        /// </summary>
        [Fact]
        public void MeterIDTest()
        {
            // TODO unit test for the property 'MeterID'
        }
        /// <summary>
        /// Test the property 'ControlledLoad'
        /// </summary>
        [Fact]
        public void ControlledLoadTest()
        {
            // TODO unit test for the property 'ControlledLoad'
        }
        /// <summary>
        /// Test the property 'ReadStartDate'
        /// </summary>
        [Fact]
        public void ReadStartDateTest()
        {
            // TODO unit test for the property 'ReadStartDate'
        }
        /// <summary>
        /// Test the property 'ReadEndDate'
        /// </summary>
        [Fact]
        public void ReadEndDateTest()
        {
            // TODO unit test for the property 'ReadEndDate'
        }
        /// <summary>
        /// Test the property 'UnitOfMeasure'
        /// </summary>
        [Fact]
        public void UnitOfMeasureTest()
        {
            // TODO unit test for the property 'UnitOfMeasure'
        }
        /// <summary>
        /// Test the property 'ReadUType'
        /// </summary>
        [Fact]
        public void ReadUTypeTest()
        {
            // TODO unit test for the property 'ReadUType'
        }
        /// <summary>
        /// Test the property 'BasicRead'
        /// </summary>
        [Fact]
        public void BasicReadTest()
        {
            // TODO unit test for the property 'BasicRead'
        }
        /// <summary>
        /// Test the property 'IntervalRead'
        /// </summary>
        [Fact]
        public void IntervalReadTest()
        {
            // TODO unit test for the property 'IntervalRead'
        }

    }

}
