/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Energy.Apis;
using Agl.Cdr.Energy.Models;
using Agl.Cdr.Energy.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Energy.Test.Model
{
    /// <summary>
    ///  Class for testing EnergyPlanContract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnergyPlanContractTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnergyPlanContract
        //private EnergyPlanContract instance;

        public EnergyPlanContractTests()
        {
            // TODO uncomment below to create an instance of EnergyPlanContract
            //instance = new EnergyPlanContract();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnergyPlanContract
        /// </summary>
        [Fact]
        public void EnergyPlanContractInstanceTest()
        {
            // TODO uncomment below to test "IsType" EnergyPlanContract
            //Assert.IsType<EnergyPlanContract>(instance);
        }


        /// <summary>
        /// Test the property 'AdditionalFeeInformation'
        /// </summary>
        [Fact]
        public void AdditionalFeeInformationTest()
        {
            // TODO unit test for the property 'AdditionalFeeInformation'
        }
        /// <summary>
        /// Test the property 'PricingModel'
        /// </summary>
        [Fact]
        public void PricingModelTest()
        {
            // TODO unit test for the property 'PricingModel'
        }
        /// <summary>
        /// Test the property 'TimeZone'
        /// </summary>
        [Fact]
        public void TimeZoneTest()
        {
            // TODO unit test for the property 'TimeZone'
        }
        /// <summary>
        /// Test the property 'IsFixed'
        /// </summary>
        [Fact]
        public void IsFixedTest()
        {
            // TODO unit test for the property 'IsFixed'
        }
        /// <summary>
        /// Test the property 'Variation'
        /// </summary>
        [Fact]
        public void VariationTest()
        {
            // TODO unit test for the property 'Variation'
        }
        /// <summary>
        /// Test the property 'OnExpiryDescription'
        /// </summary>
        [Fact]
        public void OnExpiryDescriptionTest()
        {
            // TODO unit test for the property 'OnExpiryDescription'
        }
        /// <summary>
        /// Test the property 'PaymentOption'
        /// </summary>
        [Fact]
        public void PaymentOptionTest()
        {
            // TODO unit test for the property 'PaymentOption'
        }
        /// <summary>
        /// Test the property 'IntrinsicGreenPower'
        /// </summary>
        [Fact]
        public void IntrinsicGreenPowerTest()
        {
            // TODO unit test for the property 'IntrinsicGreenPower'
        }
        /// <summary>
        /// Test the property 'ControlledLoad'
        /// </summary>
        [Fact]
        public void ControlledLoadTest()
        {
            // TODO unit test for the property 'ControlledLoad'
        }
        /// <summary>
        /// Test the property 'Incentives'
        /// </summary>
        [Fact]
        public void IncentivesTest()
        {
            // TODO unit test for the property 'Incentives'
        }
        /// <summary>
        /// Test the property 'Discounts'
        /// </summary>
        [Fact]
        public void DiscountsTest()
        {
            // TODO unit test for the property 'Discounts'
        }
        /// <summary>
        /// Test the property 'GreenPowerCharges'
        /// </summary>
        [Fact]
        public void GreenPowerChargesTest()
        {
            // TODO unit test for the property 'GreenPowerCharges'
        }
        /// <summary>
        /// Test the property 'Eligibility'
        /// </summary>
        [Fact]
        public void EligibilityTest()
        {
            // TODO unit test for the property 'Eligibility'
        }
        /// <summary>
        /// Test the property 'Fees'
        /// </summary>
        [Fact]
        public void FeesTest()
        {
            // TODO unit test for the property 'Fees'
        }
        /// <summary>
        /// Test the property 'SolarFeedInTariff'
        /// </summary>
        [Fact]
        public void SolarFeedInTariffTest()
        {
            // TODO unit test for the property 'SolarFeedInTariff'
        }
        /// <summary>
        /// Test the property 'TariffPeriod'
        /// </summary>
        [Fact]
        public void TariffPeriodTest()
        {
            // TODO unit test for the property 'TariffPeriod'
        }

    }

}
