/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Energy.Apis;
using Agl.Cdr.Energy.Models;
using Agl.Cdr.Energy.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Energy.Test.Model
{
    /// <summary>
    ///  Class for testing EnergyPlanControlledLoad
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnergyPlanControlledLoadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnergyPlanControlledLoad
        //private EnergyPlanControlledLoad instance;

        public EnergyPlanControlledLoadTests()
        {
            // TODO uncomment below to create an instance of EnergyPlanControlledLoad
            //instance = new EnergyPlanControlledLoad();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnergyPlanControlledLoad
        /// </summary>
        [Fact]
        public void EnergyPlanControlledLoadInstanceTest()
        {
            // TODO uncomment below to test "IsType" EnergyPlanControlledLoad
            //Assert.IsType<EnergyPlanControlledLoad>(instance);
        }


        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DailyCharge'
        /// </summary>
        [Fact]
        public void DailyChargeTest()
        {
            // TODO unit test for the property 'DailyCharge'
        }
        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Fact]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }
        /// <summary>
        /// Test the property 'Rates'
        /// </summary>
        [Fact]
        public void RatesTest()
        {
            // TODO unit test for the property 'Rates'
        }

    }

}
