/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Energy.Apis;
using Agl.Cdr.Energy.Models;
using Agl.Cdr.Energy.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Energy.Test.Model
{
    /// <summary>
    ///  Class for testing EnergyAccountDetailAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnergyAccountDetailAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnergyAccountDetailAllOf
        //private EnergyAccountDetailAllOf instance;

        public EnergyAccountDetailAllOfTests()
        {
            // TODO uncomment below to create an instance of EnergyAccountDetailAllOf
            //instance = new EnergyAccountDetailAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnergyAccountDetailAllOf
        /// </summary>
        [Fact]
        public void EnergyAccountDetailAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" EnergyAccountDetailAllOf
            //Assert.IsType<EnergyAccountDetailAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'Plans'
        /// </summary>
        [Fact]
        public void PlansTest()
        {
            // TODO unit test for the property 'Plans'
        }

    }

}
