/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Energy.Apis;
using Agl.Cdr.Energy.Models;
using Agl.Cdr.Energy.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Energy.Test.Model
{
    /// <summary>
    ///  Class for testing EnergyServicePoint
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnergyServicePointTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnergyServicePoint
        //private EnergyServicePoint instance;

        public EnergyServicePointTests()
        {
            // TODO uncomment below to create an instance of EnergyServicePoint
            //instance = new EnergyServicePoint();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnergyServicePoint
        /// </summary>
        [Fact]
        public void EnergyServicePointInstanceTest()
        {
            // TODO uncomment below to test "IsType" EnergyServicePoint
            //Assert.IsType<EnergyServicePoint>(instance);
        }


        /// <summary>
        /// Test the property 'ServicePointId'
        /// </summary>
        [Fact]
        public void ServicePointIdTest()
        {
            // TODO unit test for the property 'ServicePointId'
        }
        /// <summary>
        /// Test the property 'NationalMeteringId'
        /// </summary>
        [Fact]
        public void NationalMeteringIdTest()
        {
            // TODO unit test for the property 'NationalMeteringId'
        }
        /// <summary>
        /// Test the property 'ServicePointClassification'
        /// </summary>
        [Fact]
        public void ServicePointClassificationTest()
        {
            // TODO unit test for the property 'ServicePointClassification'
        }
        /// <summary>
        /// Test the property 'ServicePointStatus'
        /// </summary>
        [Fact]
        public void ServicePointStatusTest()
        {
            // TODO unit test for the property 'ServicePointStatus'
        }
        /// <summary>
        /// Test the property 'JurisdictionCode'
        /// </summary>
        [Fact]
        public void JurisdictionCodeTest()
        {
            // TODO unit test for the property 'JurisdictionCode'
        }
        /// <summary>
        /// Test the property 'IsGenerator'
        /// </summary>
        [Fact]
        public void IsGeneratorTest()
        {
            // TODO unit test for the property 'IsGenerator'
        }
        /// <summary>
        /// Test the property 'ValidFromDate'
        /// </summary>
        [Fact]
        public void ValidFromDateTest()
        {
            // TODO unit test for the property 'ValidFromDate'
        }
        /// <summary>
        /// Test the property 'LastUpdateDateTime'
        /// </summary>
        [Fact]
        public void LastUpdateDateTimeTest()
        {
            // TODO unit test for the property 'LastUpdateDateTime'
        }
        /// <summary>
        /// Test the property 'ConsumerProfile'
        /// </summary>
        [Fact]
        public void ConsumerProfileTest()
        {
            // TODO unit test for the property 'ConsumerProfile'
        }

    }

}
