/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Energy.Apis;
using Agl.Cdr.Energy.Models;
using Agl.Cdr.Energy.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Energy.Test.Model
{
    /// <summary>
    ///  Class for testing EnergyPaymentScheduleManualPayment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnergyPaymentScheduleManualPaymentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnergyPaymentScheduleManualPayment
        //private EnergyPaymentScheduleManualPayment instance;

        public EnergyPaymentScheduleManualPaymentTests()
        {
            // TODO uncomment below to create an instance of EnergyPaymentScheduleManualPayment
            //instance = new EnergyPaymentScheduleManualPayment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnergyPaymentScheduleManualPayment
        /// </summary>
        [Fact]
        public void EnergyPaymentScheduleManualPaymentInstanceTest()
        {
            // TODO uncomment below to test "IsType" EnergyPaymentScheduleManualPayment
            //Assert.IsType<EnergyPaymentScheduleManualPayment>(instance);
        }


        /// <summary>
        /// Test the property 'BillFrequency'
        /// </summary>
        [Fact]
        public void BillFrequencyTest()
        {
            // TODO unit test for the property 'BillFrequency'
        }

    }

}
