/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Energy.Apis;
using Agl.Cdr.Energy.Models;
using Agl.Cdr.Energy.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Energy.Test.Model
{
    /// <summary>
    ///  Class for testing EnergyBillingListResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnergyBillingListResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnergyBillingListResponseData
        //private EnergyBillingListResponseData instance;

        public EnergyBillingListResponseDataTests()
        {
            // TODO uncomment below to create an instance of EnergyBillingListResponseData
            //instance = new EnergyBillingListResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnergyBillingListResponseData
        /// </summary>
        [Fact]
        public void EnergyBillingListResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" EnergyBillingListResponseData
            //Assert.IsType<EnergyBillingListResponseData>(instance);
        }


        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Fact]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }

    }

}
