/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Energy.Apis;
using Agl.Cdr.Energy.Models;
using Agl.Cdr.Energy.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Energy.Test.Model
{
    /// <summary>
    ///  Class for testing EnergyAccountDetailAllOfAuthorisedContacts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnergyAccountDetailAllOfAuthorisedContactsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnergyAccountDetailAllOfAuthorisedContacts
        //private EnergyAccountDetailAllOfAuthorisedContacts instance;

        public EnergyAccountDetailAllOfAuthorisedContactsTests()
        {
            // TODO uncomment below to create an instance of EnergyAccountDetailAllOfAuthorisedContacts
            //instance = new EnergyAccountDetailAllOfAuthorisedContacts();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnergyAccountDetailAllOfAuthorisedContacts
        /// </summary>
        [Fact]
        public void EnergyAccountDetailAllOfAuthorisedContactsInstanceTest()
        {
            // TODO uncomment below to test "IsType" EnergyAccountDetailAllOfAuthorisedContacts
            //Assert.IsType<EnergyAccountDetailAllOfAuthorisedContacts>(instance);
        }


        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'MiddleNames'
        /// </summary>
        [Fact]
        public void MiddleNamesTest()
        {
            // TODO unit test for the property 'MiddleNames'
        }
        /// <summary>
        /// Test the property 'Prefix'
        /// </summary>
        [Fact]
        public void PrefixTest()
        {
            // TODO unit test for the property 'Prefix'
        }
        /// <summary>
        /// Test the property 'Suffix'
        /// </summary>
        [Fact]
        public void SuffixTest()
        {
            // TODO unit test for the property 'Suffix'
        }

    }

}
