/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Agl.Cdr.Energy.Apis;
using Agl.Cdr.Energy.Models;
using Agl.Cdr.Energy.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Agl.Cdr.Energy.Test.Model
{
    /// <summary>
    ///  Class for testing MetaPaginated
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MetaPaginatedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MetaPaginated
        //private MetaPaginated instance;

        public MetaPaginatedTests()
        {
            // TODO uncomment below to create an instance of MetaPaginated
            //instance = new MetaPaginated();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MetaPaginated
        /// </summary>
        [Fact]
        public void MetaPaginatedInstanceTest()
        {
            // TODO uncomment below to test "IsType" MetaPaginated
            //Assert.IsType<MetaPaginated>(instance);
        }


        /// <summary>
        /// Test the property 'TotalRecords'
        /// </summary>
        [Fact]
        public void TotalRecordsTest()
        {
            // TODO unit test for the property 'TotalRecords'
        }
        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Fact]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }

    }

}
