/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Agl.Cdr.Energy.Client.OpenAPIDateConverter;

namespace Agl.Cdr.Energy.Models
{
    /// <summary>
    /// EnergyInvoiceGasUsageChargesOtherCharges
    /// </summary>
    [DataContract(Name = "EnergyInvoiceGasUsageCharges_otherCharges")]
    public partial class EnergyInvoiceGasUsageChargesOtherCharges : IEquatable<EnergyInvoiceGasUsageChargesOtherCharges>, IValidatableObject
    {
        /// <summary>
        /// Type of charge. Assumed to be other if absent
        /// </summary>
        /// <value>Type of charge. Assumed to be other if absent</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum ENVIRONMENTAL for value: ENVIRONMENTAL
            /// </summary>
            [EnumMember(Value = "ENVIRONMENTAL")]
            ENVIRONMENTAL = 1,

            /// <summary>
            /// Enum REGULATED for value: REGULATED
            /// </summary>
            [EnumMember(Value = "REGULATED")]
            REGULATED = 2,

            /// <summary>
            /// Enum NETWORK for value: NETWORK
            /// </summary>
            [EnumMember(Value = "NETWORK")]
            NETWORK = 3,

            /// <summary>
            /// Enum METERING for value: METERING
            /// </summary>
            [EnumMember(Value = "METERING")]
            METERING = 4,

            /// <summary>
            /// Enum RETAILSERVICE for value: RETAIL_SERVICE
            /// </summary>
            [EnumMember(Value = "RETAIL_SERVICE")]
            RETAILSERVICE = 5,

            /// <summary>
            /// Enum RCTI for value: RCTI
            /// </summary>
            [EnumMember(Value = "RCTI")]
            RCTI = 6,

            /// <summary>
            /// Enum OTHER for value: OTHER
            /// </summary>
            [EnumMember(Value = "OTHER")]
            OTHER = 7

        }


        /// <summary>
        /// Type of charge. Assumed to be other if absent
        /// </summary>
        /// <value>Type of charge. Assumed to be other if absent</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EnergyInvoiceGasUsageChargesOtherCharges" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EnergyInvoiceGasUsageChargesOtherCharges() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EnergyInvoiceGasUsageChargesOtherCharges" /> class.
        /// </summary>
        /// <param name="type">Type of charge. Assumed to be other if absent.</param>
        /// <param name="amount">The aggregate total of charges for this item (exclusive of GST) (required).</param>
        /// <param name="description">A free text description of the type of charge (required).</param>
        public EnergyInvoiceGasUsageChargesOtherCharges(TypeEnum? type = default(TypeEnum?), string amount = default(string), string description = default(string))
        {
            // to ensure "amount" is required (not null)
            this.Amount = amount ?? throw new ArgumentNullException("amount is a required property for EnergyInvoiceGasUsageChargesOtherCharges and cannot be null");
            // to ensure "description" is required (not null)
            this.Description = description ?? throw new ArgumentNullException("description is a required property for EnergyInvoiceGasUsageChargesOtherCharges and cannot be null");
            this.Type = type;
        }

        /// <summary>
        /// The aggregate total of charges for this item (exclusive of GST)
        /// </summary>
        /// <value>The aggregate total of charges for this item (exclusive of GST)</value>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = false)]
        public string Amount { get; set; }

        /// <summary>
        /// A free text description of the type of charge
        /// </summary>
        /// <value>A free text description of the type of charge</value>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EnergyInvoiceGasUsageChargesOtherCharges {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EnergyInvoiceGasUsageChargesOtherCharges);
        }

        /// <summary>
        /// Returns true if EnergyInvoiceGasUsageChargesOtherCharges instances are equal
        /// </summary>
        /// <param name="input">Instance of EnergyInvoiceGasUsageChargesOtherCharges to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EnergyInvoiceGasUsageChargesOtherCharges input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    this.Type.Equals(input.Type)
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
