/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Agl.Cdr.Energy.Client.OpenAPIDateConverter;

namespace Agl.Cdr.Energy.Models
{
    /// <summary>
    /// EnergyServicePointListResponseData
    /// </summary>
    [DataContract(Name = "EnergyServicePointListResponse_data")]
    public partial class EnergyServicePointListResponseData : IEquatable<EnergyServicePointListResponseData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnergyServicePointListResponseData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EnergyServicePointListResponseData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EnergyServicePointListResponseData" /> class.
        /// </summary>
        /// <param name="servicePoints">servicePoints (required).</param>
        public EnergyServicePointListResponseData(List<EnergyServicePoint> servicePoints = default(List<EnergyServicePoint>))
        {
            // to ensure "servicePoints" is required (not null)
            this.ServicePoints = servicePoints ?? throw new ArgumentNullException("servicePoints is a required property for EnergyServicePointListResponseData and cannot be null");
        }

        /// <summary>
        /// Gets or Sets ServicePoints
        /// </summary>
        [DataMember(Name = "servicePoints", IsRequired = true, EmitDefaultValue = false)]
        public List<EnergyServicePoint> ServicePoints { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EnergyServicePointListResponseData {\n");
            sb.Append("  ServicePoints: ").Append(ServicePoints).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EnergyServicePointListResponseData);
        }

        /// <summary>
        /// Returns true if EnergyServicePointListResponseData instances are equal
        /// </summary>
        /// <param name="input">Instance of EnergyServicePointListResponseData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EnergyServicePointListResponseData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ServicePoints == input.ServicePoints ||
                    this.ServicePoints != null &&
                    input.ServicePoints != null &&
                    this.ServicePoints.SequenceEqual(input.ServicePoints)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ServicePoints != null)
                    hashCode = hashCode * 59 + this.ServicePoints.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
