/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * The version of the OpenAPI document: 1.15.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Agl.Cdr.Energy.Client.OpenAPIDateConverter;

namespace Agl.Cdr.Energy.Models
{
    /// <summary>
    /// EnergyPlanDetailAllOfMeteringCharges
    /// </summary>
    [DataContract(Name = "EnergyPlanDetail_allOf_meteringCharges")]
    public partial class EnergyPlanDetailAllOfMeteringCharges : IEquatable<EnergyPlanDetailAllOfMeteringCharges>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnergyPlanDetailAllOfMeteringCharges" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EnergyPlanDetailAllOfMeteringCharges() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EnergyPlanDetailAllOfMeteringCharges" /> class.
        /// </summary>
        /// <param name="displayName">Display name of the charge (required).</param>
        /// <param name="description">Description of the charge.</param>
        /// <param name="minimumValue">Minimum value of the charge if the charge is a range or the absolute value of the charge if no range is specified (required).</param>
        /// <param name="maximumValue">The upper limit of the charge if the charge could occur in a range.</param>
        /// <param name="period">The charges that occur on a schedule indicates the frequency. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax).</param>
        public EnergyPlanDetailAllOfMeteringCharges(string displayName = default(string), string description = default(string), string minimumValue = default(string), string maximumValue = default(string), string period = default(string))
        {
            // to ensure "displayName" is required (not null)
            this.DisplayName = displayName ?? throw new ArgumentNullException("displayName is a required property for EnergyPlanDetailAllOfMeteringCharges and cannot be null");
            // to ensure "minimumValue" is required (not null)
            this.MinimumValue = minimumValue ?? throw new ArgumentNullException("minimumValue is a required property for EnergyPlanDetailAllOfMeteringCharges and cannot be null");
            this.Description = description;
            this.MaximumValue = maximumValue;
            this.Period = period;
        }

        /// <summary>
        /// Display name of the charge
        /// </summary>
        /// <value>Display name of the charge</value>
        [DataMember(Name = "displayName", IsRequired = true, EmitDefaultValue = false)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Description of the charge
        /// </summary>
        /// <value>Description of the charge</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Minimum value of the charge if the charge is a range or the absolute value of the charge if no range is specified
        /// </summary>
        /// <value>Minimum value of the charge if the charge is a range or the absolute value of the charge if no range is specified</value>
        [DataMember(Name = "minimumValue", IsRequired = true, EmitDefaultValue = false)]
        public string MinimumValue { get; set; }

        /// <summary>
        /// The upper limit of the charge if the charge could occur in a range
        /// </summary>
        /// <value>The upper limit of the charge if the charge could occur in a range</value>
        [DataMember(Name = "maximumValue", EmitDefaultValue = false)]
        public string MaximumValue { get; set; }

        /// <summary>
        /// The charges that occur on a schedule indicates the frequency. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax)
        /// </summary>
        /// <value>The charges that occur on a schedule indicates the frequency. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax)</value>
        [DataMember(Name = "period", EmitDefaultValue = false)]
        public string Period { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EnergyPlanDetailAllOfMeteringCharges {\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  MinimumValue: ").Append(MinimumValue).Append("\n");
            sb.Append("  MaximumValue: ").Append(MaximumValue).Append("\n");
            sb.Append("  Period: ").Append(Period).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EnergyPlanDetailAllOfMeteringCharges);
        }

        /// <summary>
        /// Returns true if EnergyPlanDetailAllOfMeteringCharges instances are equal
        /// </summary>
        /// <param name="input">Instance of EnergyPlanDetailAllOfMeteringCharges to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EnergyPlanDetailAllOfMeteringCharges input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DisplayName == input.DisplayName ||
                    (this.DisplayName != null &&
                    this.DisplayName.Equals(input.DisplayName))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.MinimumValue == input.MinimumValue ||
                    (this.MinimumValue != null &&
                    this.MinimumValue.Equals(input.MinimumValue))
                ) && 
                (
                    this.MaximumValue == input.MaximumValue ||
                    (this.MaximumValue != null &&
                    this.MaximumValue.Equals(input.MaximumValue))
                ) && 
                (
                    this.Period == input.Period ||
                    (this.Period != null &&
                    this.Period.Equals(input.Period))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DisplayName != null)
                    hashCode = hashCode * 59 + this.DisplayName.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.MinimumValue != null)
                    hashCode = hashCode * 59 + this.MinimumValue.GetHashCode();
                if (this.MaximumValue != null)
                    hashCode = hashCode * 59 + this.MaximumValue.GetHashCode();
                if (this.Period != null)
                    hashCode = hashCode * 59 + this.Period.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
